export const NEW_PRODUCT_LIST_REQUEST = "NEW_PRODUCT_LIST_REQUEST";
export const NEW_PRODUCT_LIST_SUCCESS = "NEW_PRODUCT_LIST_SUCCESS";
export const NEW_PRODUCT_LIST_FAIL = "NEW_PRODUCT_LIST_FAIL";

export const NEW_PRODUCT_DETAILS_REQUEST = "NEW_PRODUCT_DETAILS_REQUEST";
export const NEW_PRODUCT_DETAILS_SUCCESS = "NEW_PRODUCT_DETAILS_SUCCESS";
export const NEW_PRODUCT_DETAILS_FAIL = "NEW_PRODUCT_DETAILS_FAIL";

export const NEW_PRODUCT_DELETE_REQUEST = "NEW_PRODUCT_DELETE_REQUEST";
export const NEW_PRODUCT_DELETE_SUCCESS = "NEW_PRODUCT_DELETE_SUCCESS";
export const NEW_PRODUCT_DELETE_FAIL = "NEW_PRODUCT_DELETE_FAIL";

export const NEW_PRODUCT_CREATE_REQUEST = "NEW_PRODUCT_CREATE_REQUEST";
export const NEW_PRODUCT_CREATE_SUCCESS = "NEW_PRODUCT_CREATE_SUCCESS";
export const NEW_PRODUCT_CREATE_FAIL = "NEW_PRODUCT_CREATE_FAIL";
export const NEW_PRODUCT_CREATE_RESET = "NEW_PRODUCT_CREATE_RESET";

export const NEW_PRODUCT_UPDATE_REQUEST = "NEW_PRODUCT_UPDATE_REQUEST";
export const NEW_PRODUCT_UPDATE_SUCCESS = "NEW_PRODUCT_UPDATE_SUCCESS";
export const NEW_PRODUCT_UPDATE_FAIL = "NEW_PRODUCT_UPDATE_FAIL";
export const NEW_PRODUCT_UPDATE_RESET = "NEW_PRODUCT_UPDATE_RESET";

export const NEW_PRODUCT_LIST_MY_REQUEST = "NEW_PRODUCT_LIST_MY_REQUEST";
export const NEW_PRODUCT_LIST_MY_SUCCESS = "NEW_PRODUCT_LIST_MY_SUCCESS";
export const NEW_PRODUCT_LIST_MY_FAIL = "NEW_PRODUCT_LIST_MY_FAIL";
export const NEW_PRODUCT_LIST_MY_RESET = "NEW_PRODUCT_LIST_MY_RESET";

export const NEW_PRODUCT_ADDED_DB_REQUEST = "NEW_PRODUCT_ADDED_DB_REQUEST";
export const NEW_PRODUCT_ADDED_DB_SUCCESS = "NEW_PRODUCT_ADDED_DB_SUCCESS";
export const NEW_PRODUCT_ADDED_DB_FAIL = "NEW_PRODUCT_ADDED_DB_FAIL";
export const NEW_PRODUCT_ADDED_DB_RESET = "NEW_PRODUCT_ADDED_DB_RESET";
